# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-10 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20171109_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='privacy',
            field=models.CharField(blank=True, choices=[('public', 'Public'), ('private', 'Private')], help_text="Choices: ['public', 'private']", max_length=10, null=True, verbose_name='Privacy'),
        ),
    ]
